### ISSUE TITLE
Font is too large in mobile view on screen resolutions such as Iphone 5s

### ISSUE THREAD

**Issue by ShaRay** [seanwash/sharay.com#9]
Font is too large on mobile view screen iphone 5s. Need to make a media query to adjust this

**Comment by seanwash** [comment]
You can use the chrome device emulator to test this out. Here's a quick overview: http://cl.ly/0p460z3g2k34

**Comment by seanwash** [comment]
Wow that didn't record any audio. one sec

**Comment by seanwash** [comment]
Uploading: http://cl.ly/1o1T2N0G3v0K

**Comment by ShaRay** [comment]
@media (max-width: 320px) {
  header .intro-text .intro-heading {
      font-size: 45px; } }

Fixed the font-size issue with screen widths 320px and lower.

**Comment by seanwash** [comment]
That'll fix the problem but can you select it with just `header .intro-heading`? The reason I ask is that the more specific you get with your css selectors the more complicated things get down the road.

Here's a great article on the matter: http://csswizardry.com/2012/05/keep-your-css-selectors-short/

**Comment by ShaRay** [comment]
it didn't fix it

**Comment by ShaRay** [comment]
I opened a new issue
